In [19]:
from SE2Lie import *
import numpy as np
import sympy as sy

In [20]:
theta1 = np.array([1])
theta2 = np.array([2])

e0 = so2(theta1).exp
e1 = so2(theta2).exp

In [21]:
e0

array([[ 0.54030231, -0.84147098],
       [ 0.84147098,  0.54030231]])

In [22]:
e1

array([[-0.41614684, -0.90929743],
       [ 0.90929743, -0.41614684]])

In [23]:
expMult = e0@e1
expMult


array([[-0.9899925 , -0.14112001],
       [ 0.14112001, -0.9899925 ]])

In [24]:
expMult.log

array([[ 0., -3.],
       [ 3.,  0.]])